apiVersion: v1
kind: Service
metadata:
  name: fleashop-server-svc
spec:
  selector:
    app: fleashop-server
  type: NodePort
  ports:
  - name: api
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32080
  - name: management
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 32081

